In [24]:
import pandas as pd
data = pd.read_fwf(sys.stdin, skiprows=2, names=['job-ID',
  'prior',
  'name',
  'user',
  'state',
  'queue_or_start_date',
  'queue_or_start_time',
  'queue',
  'slots'], index_col='job-ID')
data.to_csv(sys.stdout, sep='\t')

,prior,name,user,state,queue_or_start_date,queue_or_start_time,queue,slots
job-ID,,,,,,,,
9514066,0.48423,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu5,1
9514067,0.33652,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu2,1
9514068,0.25926,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu5,1
9514069,0.21712,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu2,1
9514070,0.18912,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu5,1
9514424,0.00000,fit_sfacts,bsmith,qw,12/02/2021,09:52:11,NaN,1
9514425,0.00000,fit_sfacts,bsmith,qw,12/02/2021,09:52:11,NaN,1
9514426,0.00000,compare_in,bsmith,qw,12/02/2021,09:52:11,NaN,1
9514427,0.00000,fit_sfacts,bsmith,qw,12/02/2021,09:52:11,NaN,1

In [23]:
pd.DataFrame(lines[2:], columns=['job-ID',
  'prior',
  'name',
  'user',
  'state',
  'at_date',
  'at_time',
  'queue',
  'slots'])

,job-ID,prior,name,user,state,at_date,at_time,queue,slots
0,9514066,0.48423,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu5,1
1,9514067,0.33652,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu2,1
2,9514068,0.25926,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu5,1
3,9514069,0.21712,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu2,1
4,9514070,0.18912,fit_sfacts,bsmith,r,12/02/2021,09:12:32,long.q@msg-iogpu5,1